name: 'Set version'

runs:
  using: "composite"
  steps:
    - shell: bash
      if: "startsWith(github.ref, 'refs/tags/')"
      run: |
        sed -i'' -e "s/version = [\"]0.1.0[\"]/version = \"$GITHUB_REF_NAME\"/g" pyproject.toml
        sed -i'' -e "s/version = [\"]0.1.0[\"]/version = \"$GITHUB_REF_NAME\"/g" Cargo.toml
